import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useCanvas } from '@/hooks/useCanvas';
import { Toolbar } from './Toolbar';
import { ColorPicker } from './ColorPicker';
import { StrokeWidth } from './StrokeWidth';
import { ActionBar } from './ActionBar';
import { ZoomControls } from './ZoomControls';
import { Logo } from './Logo';
export function DrawingCanvas() {
    const { canvasRef, containerRef, activeTool, setActiveTool, activeColor, setActiveColor, strokeWidth, setStrokeWidth, zoom, canUndo, canRedo, handleUndo, handleRedo, handleClear, handleExport, handleAddImage, handleZoomIn, handleZoomOut, handleZoomReset, } = useCanvas();
    return (_jsxs("div", { className: "relative w-full h-screen overflow-hidden bg-background", children: [_jsxs("div", { className: "absolute top-4 left-4 right-4 z-10 flex items-center justify-between pointer-events-none", children: [_jsx("div", { className: "pointer-events-auto", children: _jsx(Logo, {}) }), _jsx("div", { className: "pointer-events-auto flex items-center gap-3", children: _jsx(Toolbar, { activeTool: activeTool, onToolChange: setActiveTool }) }), _jsx("div", { className: "pointer-events-auto", children: _jsx(ActionBar, { canUndo: canUndo, canRedo: canRedo, onUndo: handleUndo, onRedo: handleRedo, onClear: handleClear, onExport: handleExport, onAddImage: handleAddImage }) })] }), _jsxs("div", { className: "absolute left-4 top-1/2 -translate-y-1/2 z-10 flex flex-col gap-3", children: [_jsx(ColorPicker, { activeColor: activeColor, onColorChange: setActiveColor }), _jsx(StrokeWidth, { activeWidth: strokeWidth, onWidthChange: setStrokeWidth })] }), _jsx("div", { className: "absolute bottom-4 right-4 z-10", children: _jsx(ZoomControls, { zoom: zoom, onZoomIn: handleZoomIn, onZoomOut: handleZoomOut, onZoomReset: handleZoomReset }) }), _jsx("div", { ref: containerRef, className: "canvas-container canvas-smooth w-full h-full", children: _jsx("canvas", { ref: canvasRef }) }), _jsx("div", { className: "absolute bottom-4 left-4 z-10 text-xs text-muted-foreground animate-fade-in", children: _jsxs("span", { className: "px-2 py-1 bg-card/80 backdrop-blur-sm rounded-md shadow-sm", children: ["Press ", _jsx("kbd", { className: "px-1 py-0.5 mx-0.5 bg-muted rounded text-[10px] font-mono", children: "V" }), " for Select,", _jsx("kbd", { className: "px-1 py-0.5 mx-0.5 bg-muted rounded text-[10px] font-mono", children: "P" }), " for Pencil,", _jsx("kbd", { className: "px-1 py-0.5 mx-0.5 bg-muted rounded text-[10px] font-mono", children: "R" }), " for Rectangle"] }) })] }));
}
